name: api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.4.0
  equatable: ^2.0.5
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
