name: forum_repository
description: Forum repository package for MomCare app.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.5
  http: ^1.2.2
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.9.0
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.24
  api_client:
    path: ../api_client

dev_dependencies:
  drift_dev: ^2.24.0
  build_runner: ^2.4.14
  mocktail: ^1.0.4
  test: ^1.25.0
  very_good_analysis: ^10.0.0